{ ... }:
{
  flake.nixosModules.packages =
    { pkgs, ... }:
    {
      environment.systemPackages = with pkgs; [
        ffmpegthumbnailer
        openssl
        sbctl
        niv
        android-tools
        git-repo
        fastfetch
        wget
        curl
        git
        stow
        efibootmgr
        usbutils
        vlc
        brave
        mkcert
        nss.tools
        inkscape-with-extensions
        haruna
        motrix
        htop
        ferdium
        libreoffice-stable
        pdfarranger
        ffmpeg
        yt-dlp
        libva
        libva-utils
        mpv
        bottom
        bruno
        vscode.fhs
        joplin-desktop
        gimp3-with-plugins
        google-chrome
        jq
        docker-compose
        ghostscript
        winbox
        tmux
        localsend
        kitty
        eog
        zed-editor-fhs
        nil
        nixd
        pywalfox-native
        lm_sensors
        btop
        kdePackages.kruler
      ];

    };
}
